### ISSUE TITLE
Suggest some fixes

### ISSUE THREAD

**Issue by loikein** [deathau/psuedo-wysiwyg-obsidian-theme#1]
Hi! I have been using this theme on my machine for some days (Obsidian  v0.7.6), and have come up with a couple of tweaks to improve it. However, I am not familiar with SCSS, so cannot write a PR directly 😅 My own meshed-up theme lives here: [loikein/Red-Graphite-for-Obsidian](https://github.com/loikein/Red-Graphite-for-Obsidian)

Anyways:

```css
/* plainer hr tags */
.CodeMirror-code > :not(.CodeMirror-activeline) .HyperMD-hr-bg {
  visibility: visible;
  content: "";
  width: 100%;
  height: 2px;
  display: block;
  background-color: var(--background-modifier-border);
  margin: auto;
}
.cm-s-obsidian pre.HyperMD-hr {
/* nothing here */
}

/* avoid internal link */
.CodeMirror-code > :not(.CodeMirror-activeline) .HyperMD-list-line .cm-list-1:not(.cm-hmd-internal-link)::before,
.CodeMirror-code > :not(.CodeMirror-activeline) .HyperMD-list-line .cm-list-1::before {
  /* 1st level ul bullet */
  content: "•";
  padding-right: 0.2em;
}

/* show checkbox in editor */
.CodeMirror-code > :not(.CodeMirror-activeline) .HyperMD-list-line .cm-formatting-task + .cm-list-1::before {
  content: "\02611";
}

/* indicate hyperlinked image */
.CodeMirror-code > :not(.CodeMirror-activeline) .cm-formatting-image ~ .cm-url {
  font-size: 1.5em;
}
.CodeMirror-code > :not(.CodeMirror-activeline) .cm-formatting-image ~ .cm-url::after {
  content: "\01f5bc";
  display: inline-block;
  position: absolute;
  left: 0;
  top: 0;
  font-size: 0.8em;
}

/* blockquote left boarder */
.CodeMirror-code > :not(.CodeMirror-activeline) .HyperMD-quote {
  border-left: 5px solid var(--background-modifier-border);
}
```
